power = {'BUSES': {'Area': 1.21905,
           'Bus/Area': 1.21905,
           'Bus/Gate Leakage': 0.00606939,
           'Bus/Peak Dynamic': 0.0,
           'Bus/Runtime Dynamic': 0.0,
           'Bus/Subthreshold Leakage': 0.0632911,
           'Bus/Subthreshold Leakage with power gating': 0.0237341,
           'Gate Leakage': 0.00606939,
           'Peak Dynamic': 0.0,
           'Runtime Dynamic': 0.0,
           'Subthreshold Leakage': 0.0632911,
           'Subthreshold Leakage with power gating': 0.0237341},
 'Core': [{'Area': 32.6082,
           'Execution Unit/Area': 8.2042,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.202689,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.304033,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 0.122718,
           'Execution Unit/Instruction Scheduler/Area': 2.17927,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00115349,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 1.20978,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.391717,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.017004,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.00962066,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.00730101,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 1.00996,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 0.00529112,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 2.07911,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 0.678311,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 0.0800117,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 0.0455351,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 4.84781,
           'Execution Unit/Instruction Scheduler/ROB/Area': 0.841232,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 0.000856399,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 1.55892,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 0.413051,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 0.0178624,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 0.00897339,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 1.48308,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.114878,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0641291,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.387196,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.401211,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.40222,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.150833,
           'Execution Unit/Peak Dynamic': 5.63855,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0142,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00399698,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00176968,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.102684,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.105018,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00614175,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00246675,
           'Execution Unit/Register Files/Peak Dynamic': 0.102684,
           'Execution Unit/Register Files/Runtime Dynamic': 0.119218,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.0101387,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00423643,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0442632,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00607074,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.248127,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.602737,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0920413,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0345155,
           'Execution Unit/Runtime Dynamic': 3.11297,
           'Execution Unit/Subthreshold Leakage': 1.83518,
           'Execution Unit/Subthreshold Leakage with power gating': 0.709678,
           'Gate Leakage': 0.372997,
           'Instruction Fetch Unit/Area': 5.86007,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00468128,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00468128,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00408121,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.001582,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00150846,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0149522,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0447471,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.0590479,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.100956,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00151885,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000701682,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 6.4217,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.271588,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.367022,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.180386,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.342894,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 8.95664,
           'Instruction Fetch Unit/Runtime Dynamic': 0.775139,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.932587,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.408542,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 1.44454e-05,
           'L2/Subthreshold Leakage': 0.834142,
           'L2/Subthreshold Leakage with power gating': 0.401066,
           'Load Store Unit/Area': 8.80969,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 3.46402,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.06937,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0351387,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0720454,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0720453,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 3.80562,
           'Load Store Unit/Runtime Dynamic': 1.49673,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.177652,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.355303,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.591622,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.283406,
           'Memory Management Unit/Area': 0.434579,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0630492,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0630491,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.00813591,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.399277,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0446041,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 0.666776,
           'Memory Management Unit/Runtime Dynamic': 0.107656,
           'Memory Management Unit/Subthreshold Leakage': 0.0769113,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0399462,
           'Peak Dynamic': 23.6293,
           'Renaming Unit/Area': 0.369768,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 3.33511,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.0,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 0.0414755,
           'Renaming Unit/Free List/Gate Leakage': 4.15911e-05,
           'Renaming Unit/Free List/Peak Dynamic': 0.0401324,
           'Renaming Unit/Free List/Runtime Dynamic': 0.0200302,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.000670426,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.000377987,
           'Renaming Unit/Gate Leakage': 0.00863632,
           'Renaming Unit/Int Front End RAT/Area': 0.114751,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.00038343,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 0.86945,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 0.201775,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.00611897,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.00348781,
           'Renaming Unit/Peak Dynamic': 4.56169,
           'Renaming Unit/Runtime Dynamic': 0.221807,
           'Renaming Unit/Subthreshold Leakage': 0.070483,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.0362779,
           'Runtime Dynamic': 5.71431,
           'Subthreshold Leakage': 6.21877,
           'Subthreshold Leakage with power gating': 2.58311},
          {'Area': 32.6082,
           'Execution Unit/Area': 8.2042,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.202689,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.304033,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 0.122718,
           'Execution Unit/Instruction Scheduler/Area': 2.17927,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00115349,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 1.20978,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.391041,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.017004,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.00962066,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.00730101,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 1.00996,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 0.00529112,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 2.07911,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 0.677142,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 0.0800117,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 0.0455351,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 4.84781,
           'Execution Unit/Instruction Scheduler/ROB/Area': 0.841232,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 0.000856399,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 1.55892,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 0.412259,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 0.0178624,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 0.00897339,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 1.48044,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.114878,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0641291,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.386528,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.400623,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.40222,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.150833,
           'Execution Unit/Peak Dynamic': 5.63719,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0141754,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00399698,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00176968,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.102507,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.104837,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00614175,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00246675,
           'Execution Unit/Register Files/Peak Dynamic': 0.102507,
           'Execution Unit/Register Files/Runtime Dynamic': 0.119012,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.0101387,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00423643,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0442632,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00607074,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.247699,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.601556,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0920413,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0345155,
           'Execution Unit/Runtime Dynamic': 3.10836,
           'Execution Unit/Subthreshold Leakage': 1.83518,
           'Execution Unit/Subthreshold Leakage with power gating': 0.709678,
           'Gate Leakage': 0.372997,
           'Instruction Fetch Unit/Area': 5.86007,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00467186,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00467186,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00407271,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.00157854,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00150584,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0149223,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0446674,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.0590479,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.100782,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00151885,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000701682,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 6.41062,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.270794,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.367022,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.180386,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.342302,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 8.94502,
           'Instruction Fetch Unit/Runtime Dynamic': 0.773471,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.932587,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.408542,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 1.44454e-05,
           'L2/Subthreshold Leakage': 0.834142,
           'L2/Subthreshold Leakage with power gating': 0.401066,
           'Load Store Unit/Area': 8.80969,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 3.45779,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.06639,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0351387,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0718441,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0718441,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 3.79844,
           'Load Store Unit/Runtime Dynamic': 1.49254,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.177155,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.354311,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.591622,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.283406,
           'Memory Management Unit/Area': 0.434579,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.062873,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.062873,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.00813591,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.398589,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0444724,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 0.665783,
           'Memory Management Unit/Runtime Dynamic': 0.107348,
           'Memory Management Unit/Subthreshold Leakage': 0.0769113,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0399462,
           'Peak Dynamic': 23.6081,
           'Renaming Unit/Area': 0.369768,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 3.33511,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.0,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 0.0414755,
           'Renaming Unit/Free List/Gate Leakage': 4.15911e-05,
           'Renaming Unit/Free List/Peak Dynamic': 0.0401324,
           'Renaming Unit/Free List/Runtime Dynamic': 0.0199957,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.000670426,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.000377987,
           'Renaming Unit/Gate Leakage': 0.00863632,
           'Renaming Unit/Int Front End RAT/Area': 0.114751,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.00038343,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 0.86945,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 0.201428,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.00611897,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.00348781,
           'Renaming Unit/Peak Dynamic': 4.56169,
           'Renaming Unit/Runtime Dynamic': 0.221426,
           'Renaming Unit/Subthreshold Leakage': 0.070483,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.0362779,
           'Runtime Dynamic': 5.70316,
           'Subthreshold Leakage': 6.21877,
           'Subthreshold Leakage with power gating': 2.58311},
          {'Area': 32.6082,
           'Execution Unit/Area': 8.2042,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.202689,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.304033,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 0.122718,
           'Execution Unit/Instruction Scheduler/Area': 2.17927,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00115349,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 1.20978,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.392778,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.017004,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.00962066,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.00730101,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 1.00996,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 0.00529112,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 2.07911,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 0.680149,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 0.0800117,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 0.0455351,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 4.84781,
           'Execution Unit/Instruction Scheduler/ROB/Area': 0.841232,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 0.000856399,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 1.55892,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 0.414079,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 0.0178624,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 0.00897339,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 1.48701,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.114878,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0641291,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.388244,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.401953,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.40222,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.150833,
           'Execution Unit/Peak Dynamic': 5.64069,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0142381,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00399698,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00176968,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.102962,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.105302,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00614175,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00246675,
           'Execution Unit/Register Files/Peak Dynamic': 0.102962,
           'Execution Unit/Register Files/Runtime Dynamic': 0.11954,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.0101387,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00423643,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0442632,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00607074,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.248799,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.60423,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0920413,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0345155,
           'Execution Unit/Runtime Dynamic': 3.11945,
           'Execution Unit/Subthreshold Leakage': 1.83518,
           'Execution Unit/Subthreshold Leakage with power gating': 0.709678,
           'Gate Leakage': 0.372997,
           'Instruction Fetch Unit/Area': 5.86007,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00469568,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00469568,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00409445,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.0015875,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00151261,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0149984,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0448602,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.0590479,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.10123,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00151885,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000701682,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 6.43323,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.272681,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.367022,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.180386,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.343822,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 8.96874,
           'Instruction Fetch Unit/Runtime Dynamic': 0.777595,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.932587,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.408542,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 1.44454e-05,
           'L2/Subthreshold Leakage': 0.834142,
           'L2/Subthreshold Leakage with power gating': 0.401066,
           'Load Store Unit/Area': 8.80969,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 3.47162,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.07303,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0351387,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0722914,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0722915,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 3.81439,
           'Load Store Unit/Runtime Dynamic': 1.50184,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.178258,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.356517,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.591622,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.283406,
           'Memory Management Unit/Area': 0.434579,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0632645,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0632645,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.00813591,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.399995,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0447867,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 0.667865,
           'Memory Management Unit/Runtime Dynamic': 0.108053,
           'Memory Management Unit/Subthreshold Leakage': 0.0769113,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0399462,
           'Peak Dynamic': 23.6534,
           'Renaming Unit/Area': 0.369768,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 3.33511,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.0,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 0.0414755,
           'Renaming Unit/Free List/Gate Leakage': 4.15911e-05,
           'Renaming Unit/Free List/Peak Dynamic': 0.0401324,
           'Renaming Unit/Free List/Runtime Dynamic': 0.0200845,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.000670426,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.000377987,
           'Renaming Unit/Gate Leakage': 0.00863632,
           'Renaming Unit/Int Front End RAT/Area': 0.114751,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.00038343,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 0.86945,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 0.202324,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.00611897,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.00348781,
           'Renaming Unit/Peak Dynamic': 4.56169,
           'Renaming Unit/Runtime Dynamic': 0.222411,
           'Renaming Unit/Subthreshold Leakage': 0.070483,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.0362779,
           'Runtime Dynamic': 5.72937,
           'Subthreshold Leakage': 6.21877,
           'Subthreshold Leakage with power gating': 2.58311}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 0.0,
          'Runtime Dynamic': 0.0,
          'Subthreshold Leakage': 4.252,
          'Subthreshold Leakage with power gating': 4.252},
 'L3': [{'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.0,
         'Runtime Dynamic': 1.44897e-05,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364}],
 'Processor': {'Area': 160.951,
               'Gate Leakage': 1.17347,
               'Peak Dynamic': 70.8908,
               'Peak Power': 97.5847,
               'Runtime Dynamic': 17.1469,
               'Subthreshold Leakage': 25.5205,
               'Subthreshold Leakage with power gating': 11.4113,
               'Total Cores/Area': 97.8245,
               'Total Cores/Gate Leakage': 1.11899,
               'Total Cores/Peak Dynamic': 70.8908,
               'Total Cores/Runtime Dynamic': 17.1468,
               'Total Cores/Subthreshold Leakage': 18.6563,
               'Total Cores/Subthreshold Leakage with power gating': 7.74932,
               'Total L3s/Area': 61.9075,
               'Total L3s/Gate Leakage': 0.0484137,
               'Total L3s/Peak Dynamic': 0.0,
               'Total L3s/Runtime Dynamic': 1.44897e-05,
               'Total L3s/Subthreshold Leakage': 6.80085,
               'Total L3s/Subthreshold Leakage with power gating': 3.32364,
               'Total Leakage': 26.6939,
               'Total NoCs/Area': 1.21905,
               'Total NoCs/Gate Leakage': 0.00606939,
               'Total NoCs/Peak Dynamic': 0.0,
               'Total NoCs/Runtime Dynamic': 0.0,
               'Total NoCs/Subthreshold Leakage': 0.0632911,
               'Total NoCs/Subthreshold Leakage with power gating': 0.0237341}}