power = {'BUSES': {'Area': 3.29076,
           'Bus/Area': 3.29076,
           'Bus/Gate Leakage': 0.00882817,
           'Bus/Peak Dynamic': 0.0,
           'Bus/Runtime Dynamic': 0.0,
           'Bus/Subthreshold Leakage': 0.0920594,
           'Bus/Subthreshold Leakage with power gating': 0.0345223,
           'Gate Leakage': 0.00882817,
           'Peak Dynamic': 0.0,
           'Runtime Dynamic': 0.0,
           'Subthreshold Leakage': 0.0920594,
           'Subthreshold Leakage with power gating': 0.0345223},
 'Core': [{'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.157626,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.12763,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.346726,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00604372,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0437054,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0446984,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0437054,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0507421,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0605913,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.147183,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.325555,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.0019925,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.0019925,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00173711,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000673362,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000642084,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00636419,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0190451,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0429698,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 2.73325,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.115614,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.145945,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 5.46058,
           'Instruction Fetch Unit/Runtime Dynamic': 0.329938,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 6.14696e-06,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 2.18513,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.455246,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.0756283,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.151257,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 2.40857,
           'Load Store Unit/Runtime Dynamic': 0.606503,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0268407,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0268408,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.169943,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0189879,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.869492,
           'Memory Management Unit/Runtime Dynamic': 0.0458286,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.08537,
           'Runtime Dynamic': 1.30783,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.157332,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.127365,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.34608,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00603252,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0436239,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0446156,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0436239,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0506481,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0604783,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.146878,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.324891,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00198825,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00198825,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00173326,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000671794,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000640875,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00635063,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0190096,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0428902,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 2.72819,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.115239,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.145674,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 5.45458,
           'Instruction Fetch Unit/Runtime Dynamic': 0.329164,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 6.14696e-06,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 2.1823,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.453884,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.0754022,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.150804,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 2.40507,
           'Load Store Unit/Runtime Dynamic': 0.604689,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0267605,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0267605,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.169629,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0189256,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.868876,
           'Memory Management Unit/Runtime Dynamic': 0.0456861,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.0746,
           'Runtime Dynamic': 1.30444,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.158057,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.127919,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.347676,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00606042,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0438251,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0448211,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0438251,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0508815,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0607573,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.147516,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.326316,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00199816,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00199816,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00174232,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000675531,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000643851,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00638249,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0190895,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0430878,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 2.74075,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.116035,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.146345,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 5.46948,
           'Instruction Fetch Unit/Runtime Dynamic': 0.33094,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 6.14696e-06,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 2.18838,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.4568,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.0758869,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.151773,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 2.41258,
           'Load Store Unit/Runtime Dynamic': 0.608574,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0269325,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0269324,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.17041,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0190582,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.870302,
           'Memory Management Unit/Runtime Dynamic': 0.0459906,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.10004,
           'Runtime Dynamic': 1.31183,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.157654,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.127659,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.34679,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00604502,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0437134,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0447066,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0437134,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0507516,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0606024,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.147216,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.325626,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00199298,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00199298,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00173754,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000673532,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000642177,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00636567,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0190495,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0429776,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 2.73374,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.115652,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.145971,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 5.46117,
           'Instruction Fetch Unit/Runtime Dynamic': 0.330016,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 6.14696e-06,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 2.18533,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.455337,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.0756436,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.151287,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 2.40881,
           'Load Store Unit/Runtime Dynamic': 0.606624,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0268462,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0268461,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.169974,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.018994,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.869543,
           'Memory Management Unit/Runtime Dynamic': 0.0458401,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.08631,
           'Runtime Dynamic': 1.30811,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.157799,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.127786,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.347108,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00605038,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0437535,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0447476,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0437535,
           'Execution Unit/Register Files/Runtime Dynamic': 0.050798,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.060658,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.147363,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.325948,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00199545,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00199545,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00173981,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000674482,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000642735,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00637345,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0190687,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0430171,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 2.73626,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.11584,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.146106,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 5.46415,
           'Instruction Fetch Unit/Runtime Dynamic': 0.330404,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 6.14696e-06,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 2.187,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.456142,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.0757772,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.151555,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 2.41088,
           'Load Store Unit/Runtime Dynamic': 0.607697,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0268936,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0268936,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.170131,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0190255,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.869877,
           'Memory Management Unit/Runtime Dynamic': 0.0459191,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.09202,
           'Runtime Dynamic': 1.30997,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.157523,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.127548,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.346501,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00603987,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.043677,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0446696,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.043677,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0507095,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0605519,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.147088,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.325346,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00199092,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00199092,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00173566,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000672764,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000641619,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00635912,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0190326,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0429421,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 2.73149,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.115479,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.145851,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 5.4585,
           'Instruction Fetch Unit/Runtime Dynamic': 0.329664,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 6.14696e-06,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 2.18426,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.454826,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.0755584,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.151117,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 2.40749,
           'Load Store Unit/Runtime Dynamic': 0.605943,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0268159,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.026816,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.169834,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0189657,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.869289,
           'Memory Management Unit/Runtime Dynamic': 0.0457817,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.08178,
           'Runtime Dynamic': 1.30674,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.157672,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.127684,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.346829,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00604572,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0437184,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0447119,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0437184,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0507576,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0606093,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.147245,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.325686,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00199371,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00199371,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00173822,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000673828,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00064227,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0063679,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0190544,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0429829,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 2.73408,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.115682,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.145989,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 5.46158,
           'Instruction Fetch Unit/Runtime Dynamic': 0.330076,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 6.14696e-06,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 2.18573,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.45553,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.0756755,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.151351,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 2.4093,
           'Load Store Unit/Runtime Dynamic': 0.606881,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0268575,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0268575,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.169995,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0189989,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.869606,
           'Memory Management Unit/Runtime Dynamic': 0.0458564,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.08731,
           'Runtime Dynamic': 1.30851,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 0.0,
          'Runtime Dynamic': 0.0,
          'Subthreshold Leakage': 8.504,
          'Subthreshold Leakage with power gating': 8.504},
 'L3': [{'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.0,
         'Runtime Dynamic': 6.16582e-06,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364},
        {'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.0,
         'Runtime Dynamic': 6.16582e-06,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364}],
 'Processor': {'Area': 306.928,
               'Gate Leakage': 2.06576,
               'Peak Dynamic': 63.6074,
               'Peak Power': 101.931,
               'Runtime Dynamic': 9.15744,
               'Subthreshold Leakage': 36.2577,
               'Subthreshold Leakage with power gating': 16.4696,
               'Total Cores/Area': 179.822,
               'Total Cores/Gate Leakage': 1.9601,
               'Total Cores/Peak Dynamic': 63.6074,
               'Total Cores/Runtime Dynamic': 9.15743,
               'Total Cores/Subthreshold Leakage': 22.5639,
               'Total Cores/Subthreshold Leakage with power gating': 9.54934,
               'Total L3s/Area': 123.815,
               'Total L3s/Gate Leakage': 0.0968273,
               'Total L3s/Peak Dynamic': 0.0,
               'Total L3s/Runtime Dynamic': 1.23316e-05,
               'Total L3s/Subthreshold Leakage': 13.6017,
               'Total L3s/Subthreshold Leakage with power gating': 6.64728,
               'Total Leakage': 38.3234,
               'Total NoCs/Area': 3.29076,
               'Total NoCs/Gate Leakage': 0.00882817,
               'Total NoCs/Peak Dynamic': 0.0,
               'Total NoCs/Runtime Dynamic': 0.0,
               'Total NoCs/Subthreshold Leakage': 0.0920594,
               'Total NoCs/Subthreshold Leakage with power gating': 0.0345223}}