power = {'BUSES': {'Area': 1.53196,
           'Bus/Area': 1.53196,
           'Bus/Gate Leakage': 0.00762733,
           'Bus/Peak Dynamic': 0.0,
           'Bus/Runtime Dynamic': 0.0,
           'Bus/Subthreshold Leakage': 0.0795371,
           'Bus/Subthreshold Leakage with power gating': 0.0298264,
           'Gate Leakage': 0.00762733,
           'Peak Dynamic': 0.0,
           'Runtime Dynamic': 0.0,
           'Subthreshold Leakage': 0.0795371,
           'Subthreshold Leakage with power gating': 0.0298264},
 'Core': [{'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.222462,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.178081,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.489346,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00853003,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0616829,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0630848,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0616829,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0716149,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0855146,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.205364,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.45506,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00217243,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00217243,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00187761,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000718887,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000906219,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00712869,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0213496,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0606451,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.85755,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.00177381,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.205978,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.79418,
           'Instruction Fetch Unit/Runtime Dynamic': 0.296875,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 9.49259e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.25178,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.00704198,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.00116978,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.00233972,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.25524,
           'Load Store Unit/Runtime Dynamic': 0.00938171,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.000415159,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.000415188,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.239848,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.000291335,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.84021,
           'Memory Management Unit/Runtime Dynamic': 0.000706523,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.37897,
           'Runtime Dynamic': 0.762023,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.222462,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.178082,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.489346,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00853006,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0616829,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.063085,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0616829,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0716151,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0855146,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.205364,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.455061,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00217244,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00217244,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00187763,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000718892,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00090622,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00712874,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0213497,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0606452,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.85756,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.00177532,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.205978,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.79419,
           'Instruction Fetch Unit/Runtime Dynamic': 0.296877,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 9.49259e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.25179,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.00704426,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.00117039,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.00234048,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.25525,
           'Load Store Unit/Runtime Dynamic': 0.00938474,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.000415377,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.000415322,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.239849,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.000291582,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.840211,
           'Memory Management Unit/Runtime Dynamic': 0.000706904,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.379,
           'Runtime Dynamic': 0.76203,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.22246,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.178079,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.489341,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00852993,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0616823,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.063084,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0616823,
           'Execution Unit/Register Files/Runtime Dynamic': 0.071614,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0855137,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.205361,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.455054,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00217239,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00217239,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00187757,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000718869,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000906207,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00712855,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0213493,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0606443,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.8575,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.00177045,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.205975,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.79413,
           'Instruction Fetch Unit/Runtime Dynamic': 0.296868,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 9.49259e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.25176,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.00702867,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.00116794,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.0023353,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.25521,
           'Load Store Unit/Runtime Dynamic': 0.00936397,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.000414507,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.000414402,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.239845,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.000290773,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.840204,
           'Memory Management Unit/Runtime Dynamic': 0.000705176,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.37888,
           'Runtime Dynamic': 0.761991,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.222467,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.178084,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.489356,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00853016,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0616842,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0630858,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0616842,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0716159,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0855163,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.205366,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.455066,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00217248,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00217248,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00187766,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000718905,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000906232,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00712884,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.02135,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.060646,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.8576,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.0017774,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.205981,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.79425,
           'Instruction Fetch Unit/Runtime Dynamic': 0.296883,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 9.49259e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.2518,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.00704952,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.00117101,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.00234223,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.25526,
           'Load Store Unit/Runtime Dynamic': 0.00939174,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.000415594,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.000415632,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.239852,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.000291935,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.840215,
           'Memory Management Unit/Runtime Dynamic': 0.000707567,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.37908,
           'Runtime Dynamic': 0.762048,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.22246,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.17808,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.489341,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00852996,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0616823,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0630843,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0616823,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0716143,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0855137,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.205362,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.455056,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00217241,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00217241,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00187759,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000718877,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00090621,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00712861,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0213494,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0606446,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.85751,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.00177184,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.205976,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.79414,
           'Instruction Fetch Unit/Runtime Dynamic': 0.296871,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 9.49259e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.25177,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.00703358,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.00116856,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.00233693,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.25522,
           'Load Store Unit/Runtime Dynamic': 0.00937051,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.000414724,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.000414692,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.239846,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.000291001,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.840206,
           'Memory Management Unit/Runtime Dynamic': 0.000705693,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.37891,
           'Runtime Dynamic': 0.762003,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 0.0,
          'Runtime Dynamic': 0.0,
          'Subthreshold Leakage': 8.504,
          'Subthreshold Leakage with power gating': 8.504},
 'L3': [{'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.0,
         'Runtime Dynamic': 9.52173e-08,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364},
        {'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.0,
         'Runtime Dynamic': 9.52173e-08,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364}],
 'Processor': {'Area': 253.791,
               'Gate Leakage': 1.50453,
               'Peak Dynamic': 46.8948,
               'Peak Power': 78.1977,
               'Runtime Dynamic': 3.8101,
               'Subthreshold Leakage': 29.7983,
               'Subthreshold Leakage with power gating': 13.6987,
               'Total Cores/Area': 128.444,
               'Total Cores/Gate Leakage': 1.40007,
               'Total Cores/Peak Dynamic': 46.8948,
               'Total Cores/Runtime Dynamic': 3.8101,
               'Total Cores/Subthreshold Leakage': 16.1171,
               'Total Cores/Subthreshold Leakage with power gating': 6.82096,
               'Total L3s/Area': 123.815,
               'Total L3s/Gate Leakage': 0.0968273,
               'Total L3s/Peak Dynamic': 0.0,
               'Total L3s/Runtime Dynamic': 1.90435e-07,
               'Total L3s/Subthreshold Leakage': 13.6017,
               'Total L3s/Subthreshold Leakage with power gating': 6.64728,
               'Total Leakage': 31.3028,
               'Total NoCs/Area': 1.53196,
               'Total NoCs/Gate Leakage': 0.00762733,
               'Total NoCs/Peak Dynamic': 0.0,
               'Total NoCs/Runtime Dynamic': 0.0,
               'Total NoCs/Subthreshold Leakage': 0.0795371,
               'Total NoCs/Subthreshold Leakage with power gating': 0.0298264}}