power = {'BUSES': {'Area': 1.53196,
           'Bus/Area': 1.53196,
           'Bus/Gate Leakage': 0.00762733,
           'Bus/Peak Dynamic': 0.0,
           'Bus/Runtime Dynamic': 0.0,
           'Bus/Subthreshold Leakage': 0.0795371,
           'Bus/Subthreshold Leakage with power gating': 0.0298264,
           'Gate Leakage': 0.00762733,
           'Peak Dynamic': 0.0,
           'Runtime Dynamic': 0.0,
           'Subthreshold Leakage': 0.0795371,
           'Subthreshold Leakage with power gating': 0.0298264},
 'Core': [{'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.222122,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.111061,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.185551,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.148465,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.677969,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0476951,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00853425,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0514483,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.063116,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0991434,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0716502,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0713257,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.257898,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.589074,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00181025,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00181025,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00156444,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000598899,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000906666,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00609161,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0177956,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.060675,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.85945,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000372249,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.20608,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.79644,
           'Instruction Fetch Unit/Runtime Dynamic': 0.291014,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 1.99379e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.2402,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.00147738,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.000245721,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.000490866,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.24093,
           'Load Store Unit/Runtime Dynamic': 0.00196825,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 8.72073e-05,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 8.71049e-05,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.239966,
           'Memory Management Unit/Itlb/Runtime Dynamic': 6.1137e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.839097,
           'Memory Management Unit/Runtime Dynamic': 0.000148242,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.55443,
           'Runtime Dynamic': 0.882205,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.222122,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.111061,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.185551,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.148464,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.677969,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0476951,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00853423,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0514483,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0631158,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0991434,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0716501,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0713257,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.257897,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.589073,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00181024,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00181024,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00156443,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000598896,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000906664,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00609158,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0177955,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0606749,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.85944,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000371543,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.206079,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.79643,
           'Instruction Fetch Unit/Runtime Dynamic': 0.291013,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 1.99379e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.24019,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.00147529,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.000245109,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.000490169,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.24092,
           'Load Store Unit/Runtime Dynamic': 0.00196545,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 8.69899e-05,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 8.69812e-05,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.239966,
           'Memory Management Unit/Itlb/Runtime Dynamic': 6.10213e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.839096,
           'Memory Management Unit/Runtime Dynamic': 0.000148002,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.55441,
           'Runtime Dynamic': 0.882199,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.222122,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.111061,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.185553,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.148465,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.677974,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0476951,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00853427,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0514489,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0631161,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.099144,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0716504,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0713266,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.257898,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.589075,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00181026,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00181026,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00156445,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000598903,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000906668,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00609164,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0177957,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0606752,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.85946,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000373053,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.20608,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.79645,
           'Instruction Fetch Unit/Runtime Dynamic': 0.291016,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 1.99379e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.2402,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.0014807,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.000245721,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.000491966,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.24093,
           'Load Store Unit/Runtime Dynamic': 0.00197266,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 8.72073e-05,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 8.73002e-05,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.239967,
           'Memory Management Unit/Itlb/Runtime Dynamic': 6.1271e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.839098,
           'Memory Management Unit/Runtime Dynamic': 0.000148571,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.55445,
           'Runtime Dynamic': 0.882212,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.222122,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.111061,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.185553,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.148465,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.677974,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0476951,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00853426,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0514489,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0631161,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.099144,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0716504,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0713266,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.257898,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.589075,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00181026,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00181026,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00156445,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000598902,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000906667,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00609163,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0177956,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0606751,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.85946,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000372809,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.20608,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.79645,
           'Instruction Fetch Unit/Runtime Dynamic': 0.291015,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 1.99379e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.2402,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.00147956,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.000245721,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.000491587,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.24093,
           'Load Store Unit/Runtime Dynamic': 0.00197114,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 8.72073e-05,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 8.72329e-05,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.239967,
           'Memory Management Unit/Itlb/Runtime Dynamic': 6.12311e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.839097,
           'Memory Management Unit/Runtime Dynamic': 0.000148464,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.55444,
           'Runtime Dynamic': 0.88221,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.222122,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.111061,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.185553,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.148466,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.677974,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0476951,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00853429,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0514489,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0631163,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.099144,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0716506,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0713266,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.257898,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.589076,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00181027,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00181027,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00156445,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000598904,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000906671,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00609166,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0177957,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0606753,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.85947,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000373321,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.206081,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.79646,
           'Instruction Fetch Unit/Runtime Dynamic': 0.291017,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 1.99379e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.24021,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.00148121,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.000246334,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.000492137,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.24094,
           'Load Store Unit/Runtime Dynamic': 0.00197335,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 8.74248e-05,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 8.73306e-05,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.239968,
           'Memory Management Unit/Itlb/Runtime Dynamic': 6.13171e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.839099,
           'Memory Management Unit/Runtime Dynamic': 0.000148648,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 9.55447,
           'Runtime Dynamic': 0.882215,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 0.0,
          'Runtime Dynamic': 0.0,
          'Subthreshold Leakage': 8.504,
          'Subthreshold Leakage with power gating': 8.504},
 'L3': [{'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.0,
         'Runtime Dynamic': 1.99991e-08,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364},
        {'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.0,
         'Runtime Dynamic': 1.99991e-08,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364}],
 'Processor': {'Area': 253.791,
               'Gate Leakage': 1.50453,
               'Peak Dynamic': 47.7722,
               'Peak Power': 79.0751,
               'Runtime Dynamic': 4.41104,
               'Subthreshold Leakage': 29.7983,
               'Subthreshold Leakage with power gating': 13.6987,
               'Total Cores/Area': 128.444,
               'Total Cores/Gate Leakage': 1.40007,
               'Total Cores/Peak Dynamic': 47.7722,
               'Total Cores/Runtime Dynamic': 4.41104,
               'Total Cores/Subthreshold Leakage': 16.1171,
               'Total Cores/Subthreshold Leakage with power gating': 6.82096,
               'Total L3s/Area': 123.815,
               'Total L3s/Gate Leakage': 0.0968273,
               'Total L3s/Peak Dynamic': 0.0,
               'Total L3s/Runtime Dynamic': 3.99983e-08,
               'Total L3s/Subthreshold Leakage': 13.6017,
               'Total L3s/Subthreshold Leakage with power gating': 6.64728,
               'Total Leakage': 31.3028,
               'Total NoCs/Area': 1.53196,
               'Total NoCs/Gate Leakage': 0.00762733,
               'Total NoCs/Peak Dynamic': 0.0,
               'Total NoCs/Runtime Dynamic': 0.0,
               'Total NoCs/Subthreshold Leakage': 0.0795371,
               'Total NoCs/Subthreshold Leakage with power gating': 0.0298264}}