power = {'BUSES': {'Area': 1.60807,
           'Bus/Area': 1.60807,
           'Bus/Gate Leakage': 0.00800628,
           'Bus/Peak Dynamic': 0.0,
           'Bus/Runtime Dynamic': 0.0,
           'Bus/Subthreshold Leakage': 0.0834888,
           'Bus/Subthreshold Leakage with power gating': 0.0313083,
           'Gate Leakage': 0.00800628,
           'Peak Dynamic': 0.0,
           'Runtime Dynamic': 0.0,
           'Subthreshold Leakage': 0.0834888,
           'Subthreshold Leakage with power gating': 0.0313083},
 'Core': [{'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.185132,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0925661,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.154649,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.12374,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.565064,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0397525,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00711298,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0428802,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0526048,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0826327,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0597178,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0594472,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.214948,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.490972,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00150877,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00150877,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00130389,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000499157,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000755672,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00507711,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0148319,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0505704,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.21671,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000308979,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.17176,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.03404,
           'Instruction Fetch Unit/Runtime Dynamic': 0.242548,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 1.66176e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.23968,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.00122669,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.000204053,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.000407571,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.24028,
           'Load Store Unit/Runtime Dynamic': 0.00163426,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 7.24191e-05,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 7.23242e-05,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.200003,
           'Memory Management Unit/Itlb/Runtime Dynamic': 5.07442e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.799078,
           'Memory Management Unit/Runtime Dynamic': 0.000123068,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 8.63846,
           'Runtime Dynamic': 0.735277,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.185132,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0925661,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.154652,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.12374,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.565069,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0397525,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00711299,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0428808,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0526049,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0826333,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0597179,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0594481,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.214948,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.490972,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00150877,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00150877,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.0013039,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000499158,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000755674,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00507712,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0148319,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0505704,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.21671,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000309365,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.17176,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.03405,
           'Instruction Fetch Unit/Runtime Dynamic': 0.242549,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 1.66176e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.23968,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.00122819,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.000204053,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.000408071,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.24028,
           'Load Store Unit/Runtime Dynamic': 0.00163626,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 7.24191e-05,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 7.24128e-05,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.200003,
           'Memory Management Unit/Itlb/Runtime Dynamic': 5.08074e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.799078,
           'Memory Management Unit/Runtime Dynamic': 0.00012322,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 8.63848,
           'Runtime Dynamic': 0.735281,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.185132,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0925661,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.154652,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.123741,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.565069,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0397525,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00711305,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0428808,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0526054,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0826333,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0597184,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0594481,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.21495,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.490975,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.0015088,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.0015088,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00130392,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000499167,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000755681,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0050772,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0148321,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0505709,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.21674,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.00031115,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.171762,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.03409,
           'Instruction Fetch Unit/Runtime Dynamic': 0.242553,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 1.66176e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.23969,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.00123512,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.000205278,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.000410374,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.2403,
           'Load Store Unit/Runtime Dynamic': 0.0016455,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 7.2854e-05,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 7.28215e-05,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.200005,
           'Memory Management Unit/Itlb/Runtime Dynamic': 5.11058e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.799082,
           'Memory Management Unit/Runtime Dynamic': 0.000123927,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 8.63854,
           'Runtime Dynamic': 0.735298,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.185132,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0925661,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.154652,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.12374,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.565069,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0397525,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00711301,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0428808,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0526051,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0826333,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0597181,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0594481,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.214949,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.490974,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00150878,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00150878,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00130391,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000499162,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000755676,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00507715,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.014832,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0505706,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.21672,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000310075,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.171761,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.03406,
           'Instruction Fetch Unit/Runtime Dynamic': 0.24255,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 1.66176e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.23969,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.00123098,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.000204666,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.000408998,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.24029,
           'Load Store Unit/Runtime Dynamic': 0.00163998,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 7.26365e-05,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 7.25774e-05,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.200004,
           'Memory Management Unit/Itlb/Runtime Dynamic': 5.09257e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.79908,
           'Memory Management Unit/Runtime Dynamic': 0.000123503,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 8.6385,
           'Runtime Dynamic': 0.735287,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.185132,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0925661,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.154652,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.12374,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.565069,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0397525,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.007113,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0428808,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.052605,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0826333,
           'Execution Unit/Register Files/Runtime Dynamic': 0.059718,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0594481,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.214949,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.490973,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00150878,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00150878,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.0013039,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000499161,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000755675,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00507714,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.014832,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0505706,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.21672,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000309852,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.17176,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.03406,
           'Instruction Fetch Unit/Runtime Dynamic': 0.24255,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 1.66176e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.23969,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.00123028,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.000204666,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.000408764,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.24029,
           'Load Store Unit/Runtime Dynamic': 0.00163904,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 7.26365e-05,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 7.25358e-05,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.200004,
           'Memory Management Unit/Itlb/Runtime Dynamic': 5.08891e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.79908,
           'Memory Management Unit/Runtime Dynamic': 0.000123425,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 8.6385,
           'Runtime Dynamic': 0.735286,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.185132,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0925661,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.154652,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.12374,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.565069,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0397525,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.007113,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0428808,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.052605,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0826333,
           'Execution Unit/Register Files/Runtime Dynamic': 0.059718,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0594481,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.214949,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.490973,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00150878,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00150878,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.0013039,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.00049916,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000755675,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00507714,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.014832,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0505705,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 3.21672,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.00030971,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.17176,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 6.03406,
           'Instruction Fetch Unit/Runtime Dynamic': 0.24255,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 1.66176e-08,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 1.23968,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.00122979,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.000204053,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.000408601,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 1.24028,
           'Load Store Unit/Runtime Dynamic': 0.00163839,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 7.24191e-05,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 7.25068e-05,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.200004,
           'Memory Management Unit/Itlb/Runtime Dynamic': 5.08659e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.799079,
           'Memory Management Unit/Runtime Dynamic': 0.000123373,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 8.63848,
           'Runtime Dynamic': 0.735284,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 0.0,
          'Runtime Dynamic': 0.0,
          'Subthreshold Leakage': 8.504,
          'Subthreshold Leakage with power gating': 8.504},
 'L3': [{'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.0,
         'Runtime Dynamic': 1.66686e-08,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364},
        {'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.0,
         'Runtime Dynamic': 1.66686e-08,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364}],
 'Processor': {'Area': 279.556,
               'Gate Leakage': 1.78492,
               'Peak Dynamic': 51.831,
               'Peak Power': 86.6416,
               'Runtime Dynamic': 4.41171,
               'Subthreshold Leakage': 33.0257,
               'Subthreshold Leakage with power gating': 15.0848,
               'Total Cores/Area': 154.133,
               'Total Cores/Gate Leakage': 1.68009,
               'Total Cores/Peak Dynamic': 51.831,
               'Total Cores/Runtime Dynamic': 4.41171,
               'Total Cores/Subthreshold Leakage': 19.3405,
               'Total Cores/Subthreshold Leakage with power gating': 8.18515,
               'Total L3s/Area': 123.815,
               'Total L3s/Gate Leakage': 0.0968273,
               'Total L3s/Peak Dynamic': 0.0,
               'Total L3s/Runtime Dynamic': 3.33373e-08,
               'Total L3s/Subthreshold Leakage': 13.6017,
               'Total L3s/Subthreshold Leakage with power gating': 6.64728,
               'Total Leakage': 34.8106,
               'Total NoCs/Area': 1.60807,
               'Total NoCs/Gate Leakage': 0.00800628,
               'Total NoCs/Peak Dynamic': 0.0,
               'Total NoCs/Runtime Dynamic': 0.0,
               'Total NoCs/Subthreshold Leakage': 0.0834888,
               'Total NoCs/Subthreshold Leakage with power gating': 0.0313083}}