power = {'BUSES': {'Area': 3.29076,
           'Bus/Area': 3.29076,
           'Bus/Gate Leakage': 0.00882817,
           'Bus/Peak Dynamic': 0.0,
           'Bus/Runtime Dynamic': 0.0,
           'Bus/Subthreshold Leakage': 0.0920594,
           'Bus/Subthreshold Leakage with power gating': 0.0345223,
           'Gate Leakage': 0.00882817,
           'Peak Dynamic': 0.0,
           'Runtime Dynamic': 0.0,
           'Subthreshold Leakage': 0.0920594,
           'Subthreshold Leakage with power gating': 0.0345223},
 'Core': [{'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.079406,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.039703,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.0795663,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.119245,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.271477,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0170504,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00355831,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0220616,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0263159,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0391121,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0298742,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0305853,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.168504,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.357326,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.000647131,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.000647131,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.000559256,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000214094,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00037803,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00223155,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0063616,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0252981,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 1.60918,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000132178,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.0859238,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 4.12725,
           'Instruction Fetch Unit/Runtime Dynamic': 0.119947,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 7.12756e-09,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 2.88223,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.78986,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.13124,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.26248,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 3.26997,
           'Load Store Unit/Runtime Dynamic': 1.05234,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0465774,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0465775,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.100053,
           'Memory Management Unit/Itlb/Runtime Dynamic': 2.17079e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.873681,
           'Memory Management Unit/Runtime Dynamic': 0.0465992,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 8.54238,
           'Runtime Dynamic': 1.57621,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.079406,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.039703,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.0795663,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.119245,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.271477,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0170504,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00355831,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0220616,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0263159,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0391121,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0298742,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0305853,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.168504,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.357326,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.000647132,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.000647132,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.000559258,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000214095,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00037803,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00223155,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.00636161,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0252982,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 1.60918,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000132221,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.0859239,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 4.12726,
           'Instruction Fetch Unit/Runtime Dynamic': 0.119947,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 7.12756e-09,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 2.88224,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.78986,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.13124,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.26248,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 3.26998,
           'Load Store Unit/Runtime Dynamic': 1.05234,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0465776,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0465775,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.100053,
           'Memory Management Unit/Itlb/Runtime Dynamic': 2.1715e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.873683,
           'Memory Management Unit/Runtime Dynamic': 0.0465992,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 8.5424,
           'Runtime Dynamic': 1.57621,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.079406,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.039703,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.0795663,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.119245,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.271477,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0170504,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00355831,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0220616,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0263159,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0391121,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0298742,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0305853,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.168504,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.357326,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.000647132,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.000647132,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.000559257,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000214095,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00037803,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00223155,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.00636161,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0252982,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 1.60918,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000132221,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.0859239,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 4.12726,
           'Instruction Fetch Unit/Runtime Dynamic': 0.119947,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 7.12756e-09,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 2.88223,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.78986,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.13124,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.26248,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 3.26997,
           'Load Store Unit/Runtime Dynamic': 1.05234,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0465774,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0465775,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.100053,
           'Memory Management Unit/Itlb/Runtime Dynamic': 2.1715e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.873682,
           'Memory Management Unit/Runtime Dynamic': 0.0465992,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 8.54239,
           'Runtime Dynamic': 1.57621,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.079406,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.0397028,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.0795663,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.119245,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.271477,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0170504,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00355829,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0220616,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0263157,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0391121,
           'Execution Unit/Register Files/Runtime Dynamic': 0.029874,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0305853,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.168503,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.357324,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.000647126,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.000647126,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.000559252,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000214093,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000378027,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00223153,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.00636156,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.025298,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 1.60917,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000132047,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.0859233,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 4.12725,
           'Instruction Fetch Unit/Runtime Dynamic': 0.119946,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 7.12756e-09,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 2.88223,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.789855,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.131239,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.262479,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 3.26996,
           'Load Store Unit/Runtime Dynamic': 1.05233,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0465772,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0465773,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.100052,
           'Memory Management Unit/Itlb/Runtime Dynamic': 2.16857e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.87368,
           'Memory Management Unit/Runtime Dynamic': 0.0465989,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 8.54237,
           'Runtime Dynamic': 1.5762,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.079406,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.039703,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.0795663,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.119246,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.271477,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0170504,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00355833,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0220616,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.026316,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0391121,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0298744,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0305853,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.168504,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.357327,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.000647138,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.000647138,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.000559263,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000214097,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000378032,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00223157,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.00636166,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0252983,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 1.60919,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000132831,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.0859244,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 4.12727,
           'Instruction Fetch Unit/Runtime Dynamic': 0.119949,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 7.12756e-09,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 2.88224,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.789862,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.13124,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.262481,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 3.26998,
           'Load Store Unit/Runtime Dynamic': 1.05234,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0465776,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0465776,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.100053,
           'Memory Management Unit/Itlb/Runtime Dynamic': 2.18157e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.873683,
           'Memory Management Unit/Runtime Dynamic': 0.0465995,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 8.54241,
           'Runtime Dynamic': 1.57622,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.079406,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.039703,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.0795663,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.119246,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.271477,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0170504,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.00355836,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0220616,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0263162,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0391121,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0298746,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0305853,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.168505,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.357329,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.000647147,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.000647147,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.000559272,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000214101,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000378035,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0022316,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.00636173,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0252985,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 1.6092,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000133518,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.085925,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 4.12729,
           'Instruction Fetch Unit/Runtime Dynamic': 0.11995,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 7.12756e-09,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 2.88225,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.789865,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.131241,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.262482,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 3.26999,
           'Load Store Unit/Runtime Dynamic': 1.05235,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0465778,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0465778,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.100054,
           'Memory Management Unit/Itlb/Runtime Dynamic': 2.19301e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.873685,
           'Memory Management Unit/Runtime Dynamic': 0.0465997,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 8.54244,
           'Runtime Dynamic': 1.57622,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419},
          {'Area': 25.6888,
           'Execution Unit/Area': 6.14103,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.143151,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0536818,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.079406,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.039703,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.708126,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.265547,
           'Execution Unit/Gate Leakage': 0.12351,
           'Execution Unit/Instruction Scheduler/Area': 0.0,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0,
           'Execution Unit/Integer ALUs/Area': 0.47087,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.0265291,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.0795663,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.119245,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.286303,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.107364,
           'Execution Unit/Peak Dynamic': 0.271477,
           'Execution Unit/Register Files/Area': 0.570804,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.208131,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.000232788,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0170504,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0035583,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00284507,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.00125967,
           'Execution Unit/Register Files/Gate Leakage': 0.000622708,
           'Execution Unit/Register Files/Integer RF/Area': 0.362673,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.00038992,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0220616,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0263158,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00437174,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.00175585,
           'Execution Unit/Register Files/Peak Dynamic': 0.0391121,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0298741,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.00721681,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.00301552,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0352036,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.00495789,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0305853,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.168503,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0535057,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0200646,
           'Execution Unit/Runtime Dynamic': 0.357325,
           'Execution Unit/Subthreshold Leakage': 1.25199,
           'Execution Unit/Subthreshold Leakage with power gating': 0.469807,
           'Gate Leakage': 0.280015,
           'Instruction Fetch Unit/Area': 5.98523,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.000647128,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.000647128,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00540773,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.00279284,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.000559254,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00273579,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00141387,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000214094,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00129084,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000681231,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000378029,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000663763,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000352154,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00223154,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.014215,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0073517,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.00636158,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.057776,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.030989,
           'Instruction Fetch Unit/Gate Leakage': 0.0682541,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.0226323,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 6.83558e-05,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.606827,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0252981,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.00108112,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.000499461,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 1.60918,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.000132047,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.261248,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.1284,
           'Instruction Fetch Unit/Instruction Decoder/Area': 1.85799,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 1.37404,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.0859237,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.31529,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.118234,
           'Instruction Fetch Unit/Peak Dynamic': 4.12725,
           'Instruction Fetch Unit/Runtime Dynamic': 0.119947,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.703301,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.305608,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 7.12756e-09,
           'L2/Subthreshold Leakage': 0.593748,
           'L2/Subthreshold Leakage with power gating': 0.285481,
           'Load Store Unit/Area': 8.05439,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 2.88223,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.789858,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.375602,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.178556,
           'Load Store Unit/Gate Leakage': 0.0437459,
           'Load Store Unit/Load/Store Queue/Area': 0.322079,
           'Load Store Unit/Load/Store Queue/Gate Leakage': 0.00329971,
           'Load Store Unit/Load/Store Queue/Peak Dynamic': 0.13124,
           'Load Store Unit/Load/Store Queue/Runtime Dynamic': 0.26248,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage': 0.0246015,
           'Load Store Unit/Load/Store Queue/Subthreshold Leakage with power gating': 0.0140229,
           'Load Store Unit/Peak Dynamic': 3.26997,
           'Load Store Unit/Runtime Dynamic': 1.05234,
           'Load Store Unit/Subthreshold Leakage': 0.453895,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.212713,
           'Memory Management Unit/Area': 0.559739,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0465774,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0465774,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0110828,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00631717,
           'Memory Management Unit/Gate Leakage': 0.0173421,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.100053,
           'Memory Management Unit/Itlb/Runtime Dynamic': 2.16857e-05,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0294516,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0167874,
           'Memory Management Unit/Peak Dynamic': 0.873681,
           'Memory Management Unit/Runtime Dynamic': 0.0465991,
           'Memory Management Unit/Subthreshold Leakage': 0.0942255,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0432387,
           'Peak Dynamic': 8.54238,
           'Runtime Dynamic': 1.57621,
           'Subthreshold Leakage': 3.22341,
           'Subthreshold Leakage with power gating': 1.36419}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 0.0,
          'Runtime Dynamic': 0.0,
          'Subthreshold Leakage': 8.504,
          'Subthreshold Leakage with power gating': 8.504},
 'L3': [{'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.0,
         'Runtime Dynamic': 7.14943e-09,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364},
        {'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.0,
         'Runtime Dynamic': 7.14943e-09,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364}],
 'Processor': {'Area': 306.928,
               'Gate Leakage': 2.06576,
               'Peak Dynamic': 59.7968,
               'Peak Power': 98.1202,
               'Runtime Dynamic': 11.0335,
               'Subthreshold Leakage': 36.2577,
               'Subthreshold Leakage with power gating': 16.4696,
               'Total Cores/Area': 179.822,
               'Total Cores/Gate Leakage': 1.9601,
               'Total Cores/Peak Dynamic': 59.7968,
               'Total Cores/Runtime Dynamic': 11.0335,
               'Total Cores/Subthreshold Leakage': 22.5639,
               'Total Cores/Subthreshold Leakage with power gating': 9.54934,
               'Total L3s/Area': 123.815,
               'Total L3s/Gate Leakage': 0.0968273,
               'Total L3s/Peak Dynamic': 0.0,
               'Total L3s/Runtime Dynamic': 1.42989e-08,
               'Total L3s/Subthreshold Leakage': 13.6017,
               'Total L3s/Subthreshold Leakage with power gating': 6.64728,
               'Total Leakage': 38.3234,
               'Total NoCs/Area': 3.29076,
               'Total NoCs/Gate Leakage': 0.00882817,
               'Total NoCs/Peak Dynamic': 0.0,
               'Total NoCs/Runtime Dynamic': 0.0,
               'Total NoCs/Subthreshold Leakage': 0.0920594,
               'Total NoCs/Subthreshold Leakage with power gating': 0.0345223}}